name: Test Dependency Graph

on:
  workflow_call:
    inputs:
      dependents:
        type: string
        description: "The packages to test that are dependent on us"
        default: "swift-libp2p/swift-libp2p"

jobs:
  test-dependents:
    if: contains(github.event.pull_request.labels.*.name, 'approved')
    strategy:
      fail-fast: false
      matrix:
        provider: ${{dependents}}
        os: [ubuntu-latest, macos-latest]
        swift-version: ['6.0']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: '${{ matrix.swift-version }}'
      - name: Check out ${{ github.event.repository.name }}
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}
      - name: Check out provider
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.provider }}
          path: provider
          ref: ${{ matrix.ref }}
      - name: Use local ${{ github.event.repository.name }}
        run: swift package --package-path ./provider edit ${{ github.event.repository.name }} --path ./${{ github.event.repository.name }}
      - name: Run tests
        env:
            SWIFT_DETERMINISTIC_HASHING: 1
        run: swift test --package-path ./provider
